# Generated by Django 2.2.3 on 2019-08-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rise_and_fall', models.IntegerField()),
            ],
        ),
    ]
