# Generated by Django 2.2.1 on 2019-08-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesstiming', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
